---
title: "Visualização de dados"
description: |
  Neste post (em andamento) reuno algumas visualizações desenvolvidas para descrever dados simples.
author:
  - name: Beatriz Schindler
    url: https://www.linkedin.com/in/beatriz-schindler/
date: 2022-01-28
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Durante algumas consultorias prestadas, recebi com frequencia a pergunta *"o que fazer para substituir os gráficos de pizza do meu trabalho?"* 

Aqui estão algumas soluções que encontrei para esta substituição e para descrever uma característica sem levar em conta sua relação com outros fatores. 

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tibble)
```

```{r}
mtcars <- rownames_to_column(mtcars, "Tipo")
mutate(mtcars, Tipo = fct_reorder(Tipo, mpg)) %>% 
ggplot(aes(x=Tipo, y=mpg)) +
  geom_segment( aes(x=Tipo, xend=Tipo, y=0, yend=mpg), color="darkslategray") +
  geom_point(color="deepskyblue4", size=4) +
  coord_flip() +
  theme_minimal() 
```

