usethis::create_package("portfolioBeatriz")
#usethis::use_git_config(user.name = "beatrizschindler", user.email = "beapschindler@gmail.com")
#usethis::create_github_token()
#gitcreds::gitcreds_set()
usethis::use_git()
usethis::use_github()
usethis::use_github_pages("main", "/docs")
file.create(".nojekyll")
distill::create_blog(".", "Portfolio de Beatriz", gh_pages=T)
distill::create_post("Visualização de dados")
